### ISSUE TITLE
合约如何部署？

### ISSUE THREAD

**Issue by winsonlaw** [shengjian-tech/opennft#7]
readme里面这段理解不了！

并完善`nft_chain_plat`,和`nft_user_chainplat`表中的信息
- passwd:安全码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
- address: 用户超级链的ak地址
- EVMAddress: 使用Account.xchainAKToEVMAddress(address)转换获取
passwd，address字段我都知道在好里，EVMAddress我在那里获取填到数据库里面？

错误日志如下：

----------------------starting----------------------
----------------------started----------------------
2022-05-18 17:22:40.081 ERROR 15104 --- [           main] n.s.m.timer.UpdateContractExpireTimer    : 合约未知异常!

net.shengjian.makerone.exception.NFTException: 合约未知异常!
	at net.shengjian.makerone.exception.NFTException.NFTExceptionERC1155(NFTException.java:28)
	at net.shengjian.makerone.strategy.impl.XuperChainClientExecStrategyImpl.queryPlatChainMethod(XuperChainClientExecStrategyImpl.java:98)
	at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.query(ChainExecStrategyContext.java:87)
	at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.rootQuery(ChainExecStrategyContext.java:221)
	at net.shengjian.makerone.timer.UpdateContractExpireTimer.init(UpdateContractExpireTimer.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at net.shengjian.makerone.SpringrainApplication.main(SpringrainApplication.java:17)

2022-05-18 17:22:40,081 [main] net.shengjian.makerone.timer.UpdateContractExpireTimer:51-合约未知异常!
net.shengjian.makerone.exception.NFTException: 合约未知异常!
	at net.shengjian.makerone.exception.NFTException.NFTExceptionERC1155(NFTException.java:28)
	at net.shengjian.makerone.strategy.impl.XuperChainClientExecStrategyImpl.queryPlatChainMethod(XuperChainClientExecStrategyImpl.java:98)
	at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.query(ChainExecStrategyContext.java:87)
	at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.rootQuery(ChainExecStrategyContext.java:221)
	at net.shengjian.makerone.timer.UpdateContractExpireTimer.init(UpdateContractExpireTimer.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at net.shengjian.makerone.SpringrainApplication.main(SpringrainApplication.java:17)
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:22:50 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:00 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:10 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:20 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:30 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:40 CST 2022]

请问有合约的部署流程吗？

**Comment by shendengnian** [comment]
readme里面这段理解不了！

并完善nft_chain_plat,和nft_user_chainplat表中的信息

passwd:安全码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
address: 用户超级链的ak地址
EVMAddress: 使用Account.xchainAKToEVMAddress(address)转换获取
passwd，address字段我都知道在好里，EVMAddress我在那里获取填到数据库里面？
错误日志如下：

----------------------starting----------------------
----------------------started----------------------
2022-05-18 17:22:40.081 ERROR 15104 --- [ main] n.s.m.timer.UpdateContractExpireTimer : 合约未知异常!

net.shengjian.makerone.exception.NFTException: 合约未知异常!
at net.shengjian.makerone.exception.NFTException.NFTExceptionERC1155(NFTException.java:28)
at net.shengjian.makerone.strategy.impl.XuperChainClientExecStrategyImpl.queryPlatChainMethod(XuperChainClientExecStrategyImpl.java:98)
at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.query(ChainExecStrategyContext.java:87)
at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.rootQuery(ChainExecStrategyContext.java:221)
at net.shengjian.makerone.timer.UpdateContractExpireTimer.init(UpdateContractExpireTimer.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
at net.shengjian.makerone.SpringrainApplication.main(SpringrainApplication.java:17)

2022-05-18 17:22:40,081 [main] net.shengjian.makerone.timer.UpdateContractExpireTimer:51-合约未知异常!
net.shengjian.makerone.exception.NFTException: 合约未知异常!
at net.shengjian.makerone.exception.NFTException.NFTExceptionERC1155(NFTException.java:28)
at net.shengjian.makerone.strategy.impl.XuperChainClientExecStrategyImpl.queryPlatChainMethod(XuperChainClientExecStrategyImpl.java:98)
at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.query(ChainExecStrategyContext.java:87)
at net.shengjian.makerone.strategy.context.ChainExecStrategyContext.rootQuery(ChainExecStrategyContext.java:221)
at net.shengjian.makerone.timer.UpdateContractExpireTimer.init(UpdateContractExpireTimer.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
at net.shengjian.makerone.SpringrainApplication.main(SpringrainApplication.java:17)
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:22:50 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:00 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:10 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:20 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:30 CST 2022]
net.shengjian.makerone.timer.NftOrderTimer.cancelOrder=>[0/10 * * * * ?],当前时间==>[Wed May 18 17:23:40 CST 2022]

请问有合约的部署流程吗？+1
